### 準備環境  
我的numpy常常壞掉所以有時需要以下步驟  

pip uninstall numpy -y  
pip uninstall pandas -y  
pip install numpy  
pip install pandas

In [33]:
import pandas as pd

### 讀取檔案，預覽前三筆

In [34]:
file = '2015.csv'
df = pd.read_csv(file)

df.head(3)

,RptNo,RptName,StatCourseNo,StatCourseName,DataDate,PlaceNo,PlaceName,PeriodNo,PeriodName,Complex1,...,Complex5,Complex5Name,DeriveNo,DeriveExplain,FValue,SValue,RptDeptNo,RptDeptName,CreateTime,ModifyTime
0,10440-01-01-2,臺中市高級中等學校教育經費概況(預、決算數),1044001a013,高級中等學校教育經費概況(預、決算數)-預算數-經費來源(單位:千元),2015/1/1 上午 12:00:00,10000066000,臺中市,Y,年,230010000101,...,0,NaN,0,NaN,4233275,NaN,387040000E,教育局,2016/12/16 上午 09:38:58,2017/3/9 下午 01:27:27
1,10440-01-01-2,臺中市高級中等學校教育經費概況(預、決算數),1044001a013,高級中等學校教育經費概況(預、決算數)-預算數-經費來源(單位:千元),2015/1/1 上午 12:00:00,10000066000,臺中市,Y,年,230010000102,...,0,NaN,0,NaN,2231696,NaN,387040000E,教育局,2016/12/16 上午 09:38:58,2017/3/9 下午 01:27:27
2,10440-01-01-2,臺中市高級中等學校教育經費概況(預、決算數),1044001a013,高級中等學校教育經費概況(預、決算數)-預算數-經費來源(單位:千元),2015/1/1 上午 12:00:00,10000066000,臺中市,Y,年,2300100002,...,0,NaN,0,NaN,7219409,NaN,387040000E,教育局,2016/12/16 上午 09:38:58,2017/3/9 下午 01:27:27

### 簡化資料
單獨取出款項名稱與金額，將金額依照款項名稱分組，加總金額，加上index

In [35]:
pd.read_csv(file)[['Complex2Name', 'FValue']].groupby(['Complex2Name'])['FValue'].sum().reset_index()

  Complex2Name    FValue
0         償還借款    569998
1     折舊、折耗及攤銷    947209
2         經常支出  24645292
3     經常支出報廢金額    534787
4         資本支出   4714075

### 取得資料開始與截止年

In [36]:
Yfrom = int(input('資料的開始年'))
Yend = int(input('資料最後一年'))

year = []
for i in range(Yfrom,Yend+1):
    year.append(str(i))

### 串接每一年的結果

In [37]:
### 第一筆
result = pd.read_csv(year[0]+'.csv')[['Complex2Name', 'FValue']].groupby(['Complex2Name'])['FValue'].sum().reset_index()
result['year'] = year[0]

### concat 剩下年份
for j in range(1,len(year)):
    new = pd.read_csv(year[j]+'.csv')[['Complex2Name', 'FValue']].groupby(['Complex2Name'])['FValue'].sum().reset_index()
    new['year'] = year[j]
    result = pd.concat([result,new])

result

  Complex2Name    FValue  year
0         償還借款    569998  2015
1     折舊、折耗及攤銷    947209  2015
2         經常支出  24645292  2015
3     經常支出報廢金額    534787  2015
4         資本支出   4714075  2015
0         償還借款   1014559  2016
1     折舊、折耗及攤銷    975539  2016
2         經常支出  24209205  2016
3     經常支出報廢金額    357410  2016
4         資本支出   5365361  2016
0         償還借款   1513842  2017
1     折舊、折耗及攤銷    116655  2017
2         經常支出  23061479  2017
3     經常支出報廢金額    566751  2017
4         資本支出   5574950  2017
0         償還借款   2568559  2018
1     折舊、折耗及攤銷    189090  2018
2         經常支出  23744400  2018
3     經常支出報廢金額   5724945  2018
4         資本支出   5319702  2018